//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace Guncho.XML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class realmIndex {
        
        private realmIndexRealm[] realmsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("realm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public realmIndexRealm[] realms {
            get {
                return this.realmsField;
            }
            set {
                this.realmsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class realmIndexRealm {
        
        private realmIndexRealmAccess[] accessField;
        
        private string nameField;
        
        private string srcField;
        
        private string ownerField;
        
        private privacyType privacyField;
        
        private string factoryField;
        
        public realmIndexRealm() {
            this.privacyField = privacyType.@public;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("access", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public realmIndexRealmAccess[] access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(privacyType.@public)]
        public privacyType privacy {
            get {
                return this.privacyField;
            }
            set {
                this.privacyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string factory {
            get {
                return this.factoryField;
            }
            set {
                this.factoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class realmIndexRealmAccess {
        
        private string playerField;
        
        private levelType levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string player {
            get {
                return this.playerField;
            }
            set {
                this.playerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public levelType level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    public enum levelType {
        
        /// <remarks/>
        banned,
        
        /// <remarks/>
        hidden,
        
        /// <remarks/>
        visible,
        
        /// <remarks/>
        invited,
        
        /// <remarks/>
        viewSource,
        
        /// <remarks/>
        editSource,
        
        /// <remarks/>
        editSettings,
        
        /// <remarks/>
        editAccess,
        
        /// <remarks/>
        safetyOff,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    public enum privacyType {
        
        /// <remarks/>
        @private,
        
        /// <remarks/>
        hidden,
        
        /// <remarks/>
        @public,
        
        /// <remarks/>
        joinable,
        
        /// <remarks/>
        viewable,
    }
}
